### ISSUE TITLE
Couldn't open nogui file?

### ISSUE THREAD

**Issue by ahitt6345** [hawkfalcon/AutoMCServer#1]
I already posted in bukkit, but then I saw post here so why not give it a shot. 
I tried create a server and it didn't work.
Whenever I try to open/run the start.sh file it gives me the following error in my terminal:

```
Last login: Fri Mar 13 12:11:41 on ttys000
My-Macbook-Air:~ Me$ /Users/Me/Desktop/minecraft/start.sh ; exit; 
Unable to access jarfile nogui
logout

[Process completed]
```

Here is your start.sh file:

```
#!/bin/sh
cd "$( dirname "$0" )"
java -Xms1024M -Xmx1024M -jar  nogui -o true
```

I am using an 11 inch MacBook Air with 4gb of ram. So memory is not the problem.
I am using the latest version of Java (8)
I ran your Xcode project in Xcode in order to get the application to run.
I tried running the server with spigot, This worked when I tried vanilla. 
I went back to spigot and tried again but it did not work.
I am willing to provide more information if asked.

**Comment by ahitt6345** [comment]
also, in the XCode console I got a long string telling me that I did not update my java which I think is wierd. 

```
*** WARNING *** You are not using Java 7 or above. Although this will work, it is highly discouraged due to the security issues present.
*** WARNING *** Use java -version to check your version and update as soon as possible.
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
    at org.objectweb.asm.ClassReader.readLabel(ClassReader.java:2175)
    at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1171)
    at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1017)
    at org.objectweb.asm.ClassReader.accept(ClassReader.java:693)
    at org.objectweb.asm.ClassReader.accept(ClassReader.java:506)
    at net.md_5.ss.repo.RuntimeRepo.getClass0(RuntimeRepo.java:27)
    at net.md_5.ss.repo.ClassRepo.getClass(ClassRepo.java:22)
    at net.md_5.ss.repo.AggregateRepo.getClass0(AggregateRepo.java:30)
    at net.md_5.ss.repo.ClassRepo.getClass(ClassRepo.java:22)
    at net.md_5.ss.remapper.EnhancedRemapper.findMethodDeclarer(EnhancedRemapper.java:67)
    at net.md_5.ss.remapper.EnhancedRemapper.mapMethodName(EnhancedRemapper.java:33)
    at net.md_5.ss.remapper.MethodRemapper.visitMethodInsn(MethodRemapper.java:120)
    at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1416)
    at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1017)
    at org.objectweb.asm.ClassReader.accept(ClassReader.java:693)
    at org.objectweb.asm.ClassReader.accept(ClassReader.java:506)
    at net.md_5.ss.model.ClassInfo.remap(ClassInfo.java:120)
    at net.md_5.ss.SpecialSource.map(SpecialSource.java:96)
    at net.md_5.ss.SpecialSource.main(SpecialSource.java:44)
Exception in thread "main" java.lang.RuntimeException: Error running command, return status !=0: [java, -jar, BuildData/bin/SpecialSource-2.jar, map, -i, work/minecraft_server.1.8.3.jar, -m, BuildData/mappings/bukkit-1.8.3-cl.csrg, -o, work/mapped.73f3c166.jar-cl]
    at org.spigotmc.builder.Builder.runProcess(Builder.java:488)
    at org.spigotmc.builder.Builder.main(Builder.java:269)

```

Maybe this can help?

**Comment by hawkfalcon** [comment]
You need java 7 or 8. http://www.java.com/en/download/help/mac_install.xml
Edit: You say you are "I am using the latest version of Java (8)"
But your error tells me "You are not using Java 7 or above."
What does 'java -version' give you?

**Comment by ahitt6345** [comment]
That is the problem, I already did and went through that update java install wizard thing and downloaded java 8 update 40 but it still says I have java 6 when I do `java -version` but when I go into system preferences and go into the java panel it says I have java 8. and runtime environment 1.8. Both up-to-date.

**Comment by ahitt6345** [comment]
![screen shot 2015-03-13 at 4 34 20 pm](https://cloud.githubusercontent.com/assets/10404602/6649016/f215859c-c99e-11e4-8939-7bbc07b440a7.png)
Here's a photo of my java version

**Comment by ahitt6345** [comment]
![screen shot 2015-03-13 at 4 35 51 pm](https://cloud.githubusercontent.com/assets/10404602/6649029/1338eea8-c99f-11e4-888d-de36b8eacc90.png)
Here is `java -version`
very contradicting.

**Comment by hawkfalcon** [comment]
What does 
`'/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java' -version`
say?

**Comment by ahitt6345** [comment]
java 1.8

**Comment by ahitt6345** [comment]
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

**Comment by hawkfalcon** [comment]
Woo, you have a linking issue. Follow this, start at step 7 then do it again!
https://gist.github.com/johan/10590467#step-7

**Comment by ahitt6345** [comment]
It seems to be downloading ok now. I will tell if it works. It did not stop after 10 seconds. Thank you hawk.

**Comment by hawkfalcon** [comment]
Np. Java is annoying on Macs. Might make a script to auto-do it for you.

**Comment by ahitt6345** [comment]
is it normal for it to be downloading 130%?

**Comment by ahitt6345** [comment]
108?

**Comment by ahitt6345** [comment]
It officially worked. The server is running and I can get on, thanks.

**Comment by hawkfalcon** [comment]
Its a bug on some systems... haha. What'd it get to? Yay!

**Comment by ahitt6345** [comment]
Yay. no more issue gonna close this
